apiVersion: v1
kind: Service
metadata:
  name: mimuc-service
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 3000
  selector:
    app: mimuc-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimuc-app
spec:
  replicas: 3
  # type: use rolling update strategy
  # maxSurge: define how many additional pods can be started
  # maxUnavailable: define how many pods can be stopped from the current number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mimuc-app
  template:
    metadata:
      labels:
        app: mimuc-app
    spec:
      containers:
        - name: mimuc-app
          image: mimuc/helloworld:v0.0.1 # change this to v0.0.2
          ports:
            - containerPort: 3000
